// قاموس الترجمات للسياحة
const tourismTranslations = {
    ar: {
        brand_name: 'أوتشوبا',
        tourism_site_title: 'أوتشوبا للسياحة في روسيا',
        tourism_subtitle: 'للسياحة في روسيا',
        tourism: 'السياحة',
        study: 'الدراسة',
        contact: 'اتصل بنا',
        discover_russia: 'اكتشف روسيا',
        tourism_hero_title: 'اكتشف روسيا',
        tourism_hero_subtitle: 'رحلات سياحية مميزة في أجمل المدن الروسية',
        tourism_services: 'خدماتنا السياحية',
        tourism_footer_description: 'خدمات سياحية متكاملة في روسيا',
        tourism_title: "رحلة لا تُنسى في روسيا",
        tourism_description: "استكشف جمال روسيا الساحر، من القصور التاريخية إلى المناظر الطبيعية الخلابة",
        popular_destinations: 'وجهات سياحية شهيرة',
        discover_places: 'اكتشف أجمل الأماكن في روسيا',
        destinations_description: 'تعرف على المعالم الشهيرة والأماكن الساحرة في روسيا',
        moscow: 'موسكو',
        moscow_description: 'عاصمة روسيا النابضة بالحياة والتاريخ',
        landmarks: 'معلم سياحي',
        restaurants: 'مطعم',
        hotels: 'فندق',
        main_attractions: 'أبرز المعالم',
        red_square: 'الساحة الحمراء',
        kremlin: 'الكرملين',
        st_basil: 'كاتدرائية القديس باسيل',
        best_time: 'أفضل وقت للزيارة: مايو-سبتمبر',
        language: 'اللغة: الروسية',
        currency: 'العملة: الروبل الروسي',
        saint_petersburg: 'سانت بطرسبرغ',
        petersburg_description: 'مدينة القصور والفن والثقافة',
        hermitage: 'متحف الإرميتاج',
        peterhof: 'قصر بيترهوف',
        church_spilled_blood: 'كنيسة الدم المسفوك',
        best_time_spb: 'أفضل وقت للزيارة: يونيو-أغسطس',
        white_nights: 'الليالي البيضاء: مايو-يوليو',
        moscow_distance: '4 ساعات من موسكو بالقطار',
        sochi: 'سوتشي',
        sochi_description: 'مدينة ساحلية جميلة على البحر الأسود',
        beaches: 'شاطئ',
        ski_resorts: 'منتجع تزلج',
        rosa_khutor: 'منتجع روزا خوتور',
        olympic_park: 'الحديقة الأولمبية',
        dendrarium: 'حديقة دندراريوم النباتية',
        best_time_sochi: 'صيف للشواطئ، شتاء للتزلج',
        climate: 'مناخ معتدل على مدار السنة',
        moscow_flight: 'ساعتان طيران من موسكو',
        explore_destination: 'استكشف الوجهة',
        view_all_destinations: 'عرض جميع الوجهات',
        destinations: 'وجهة سياحية',
        tourists: 'سائح سنوياً',
        tours: 'رحلة منظمة',
        explore_now: 'استكشف الآن',
        book_trip: 'احجز رحلتك',
        sochi_offers: 'عروض سوتشي المميزة',
        sochi_offers_subtitle: 'اكتشف أفضل العروض السياحية في سوتشي',
        hero_badge: 'اكتشف روسيا',
        hero_title: 'رحلة استثنائية في',
        hero_title_highlight: 'روسيا الساحرة',
        hero_subtitle: 'استكشف جمال روسيا الخلاب، من القصور التاريخية إلى المناظر الطبيعية الخلابة والثقافة الغنية',
        historic_palaces: 'قصور تاريخية',
        winter_views: 'مناظر شتوية',
        russian_culture: 'ثقافة روسية',
        explore_destinations: 'استكشف الوجهات',
        book_your_trip: 'احجز رحلتك',
        special_offers: "عروض خاصة",
        winter_special: "عرض الشتاء",
        winter_duration: "ديسمبر - فبراير",
        ski_adventure: "مغامرة التزلج",
        winter_price: "500$",
        per_person: "/للشخص",
        ski_equipment: "معدات التزلج كاملة",
        ski_instructor: "مدرب تزلج محترف",
        mountain_resort: "إقامة في منتجع جبلي",
        hot_drinks: "مشروبات ساخنة مجانية",
        summer_special: "عرض الصيف",
        summer_duration: "يونيو - أغسطس",
        beach_vacation: "عطلة شاطئية",
        summer_price: "600$",
        beach_access: "دخول للشواطئ الخاصة",
        water_sports: "رياضات مائية",
        seaside_hotel: "فندق مطل على البحر",
        beach_activities: "أنشطة شاطئية",
        adventure_special: "عرض المغامرات",
        adventure_duration: "طوال العام",
        adventure_package: "باقة المغامرات",
        adventure_price: "700$",
        hiking: "رحلات المشي لمسافات طويلة",
        camping: "تخييم في الطبيعة",
        rafting: "تجديف في الأنهار",
        photography: "جولات تصوير",
        book_now: "احجز الآن",
        view_all_offers: "عرض جميع العروض",
        special_offers_badge: "عروض حصرية",
        special_offers: "عروضنا المميزة",
        special_offers_subtitle: "اكتشف باقات سفر متكاملة بأسعار تنافسية",
        moscow_package: "باقة موسكو",
        moscow_package_title: "رحلة موسكو الشاملة",
        hotel_5_stars: "فندق 5 نجوم لمدة 7 ليالي",
        guided_tours_included: "جولات سياحية مع مرشد",
        transfers_included: "خدمة التوصيل من وإلى المطار",
        moscow_price: "$1,499",
        petersburg_package: "باقة سانت بطرسبرغ",
        petersburg_package_title: "سحر سانت بطرسبرغ",
        hotel_4_stars: "فندق 4 نجوم لمدة 5 ليالي",
        museum_tickets: "تذاكر المتاحف الشهيرة",
        river_cruise: "رحلة بحرية في نهر نيفا",
        petersburg_price: "$1,299",
        russia_tour_package: "الجولة الشاملة",
        russia_tour_title: "اكتشف روسيا",
        three_cities: "زيارة 3 مدن رئيسية",
        all_transfers: "جميع التنقلات بين المدن",
        full_support: "دعم على مدار الساعة",
        russia_tour_price: "$2,499",
        book_now: "احجز الآن",
        premium_services_badge: "خدمات متميزة",
        premium_services: "خدماتنا المتميزة",
        premium_services_subtitle: "نقدم لكم مجموعة من الخدمات عالية الجودة",
        accommodation_service: "خدمات الإقامة",
        accommodation_description: "حجز فنادق فاخرة وشقق مفروشة في أفضل المواقع",
        luxury_hotels: "فنادق 5 نجوم",
        furnished_apartments: "شقق مفروشة راقية",
        best_locations: "مواقع متميزة",
        flight_service: "حجز الطيران",
        flight_description: "حجز تذاكر طيران على جميع شركات الطيران العالمية",
        best_prices: "أفضل الأسعار",
        multiple_airlines: "خيارات متعددة",
        flexible_dates: "مواعيد مرنة",
        transport_service: "خدمات النقل",
        transport_description: "توفير وسائل نقل مريحة وآمنة لجميع رحلاتكم",
        airport_transfers: "توصيل المطار",
        city_tours: "جولات المدينة",
        private_drivers: "سائق خاص",
    },
    en: {
        brand_name: 'Uchoba',
        tourism_site_title: 'Uchoba Tourism in Russia',
        tourism_subtitle: 'Tourism in Russia',
        tourism: 'Tourism',
        study: 'Study',
        contact: 'Contact Us',
        discover_russia: 'Discover Russia',
        tourism_hero_title: 'Discover Russia',
        tourism_hero_subtitle: 'Exceptional tours in the most beautiful Russian cities',
        tourism_services: 'Our Tourism Services',
        tourism_footer_description: 'Comprehensive tourism services in Russia',
        tourism_title: "Unforgettable Journey in Russia",
        tourism_description: "Explore Russia's enchanting beauty, from historic palaces to breathtaking landscapes",
        popular_destinations: 'Popular Destinations',
        discover_places: 'Discover Beautiful Places in Russia',
        destinations_description: 'Explore famous landmarks and enchanting places in Russia',
        moscow: 'Moscow',
        moscow_description: 'Russia\'s vibrant and historic capital',
        landmarks: 'Landmark',
        restaurants: 'Restaurant',
        hotels: 'Hotel',
        main_attractions: 'Main Attractions',
        red_square: 'Red Square',
        kremlin: 'The Kremlin',
        st_basil: 'Saint Basil\'s Cathedral',
        best_time: 'Best Time to Visit: May-September',
        language: 'Language: Russian',
        currency: 'Currency: Russian Ruble',
        saint_petersburg: 'Saint Petersburg',
        petersburg_description: 'City of palaces, art, and culture',
        hermitage: 'The Hermitage Museum',
        peterhof: 'Peterhof Palace',
        church_spilled_blood: 'Church of the Savior on Spilled Blood',
        best_time_spb: 'Best Time to Visit: June-August',
        white_nights: 'White Nights: May-July',
        moscow_distance: '4 hours from Moscow by train',
        sochi: 'Sochi',
        sochi_description: 'Beautiful coastal city on the Black Sea',
        beaches: 'Beach',
        ski_resorts: 'Ski Resort',
        rosa_khutor: 'Rosa Khutor Resort',
        olympic_park: 'Olympic Park',
        dendrarium: 'Dendrarium Botanical Garden',
        best_time_sochi: 'Summer for beaches, Winter for skiing',
        climate: 'Moderate climate year-round',
        moscow_flight: '2 hours flight from Moscow',
        explore_destination: 'Explore Destination',
        view_all_destinations: 'View All Destinations',
        destinations: 'Destinations',
        tourists: 'Annual Tourists',
        tours: 'Organized Tours',
        explore_now: 'Explore Now',
        book_trip: 'Book Your Trip',
        sochi_offers: 'Special Sochi Offers',
        sochi_offers_subtitle: 'Discover the best tourism offers in Sochi',
        hero_badge: 'Discover Russia',
        hero_title: 'Exceptional Journey in',
        hero_title_highlight: 'Magical Russia',
        hero_subtitle: 'Explore Russia\'s stunning beauty, from historic palaces to breathtaking landscapes and rich culture',
        historic_palaces: 'Historic Palaces',
        winter_views: 'Winter Views',
        russian_culture: 'Russian Culture',
        explore_destinations: 'Explore Destinations',
        book_your_trip: 'Book Your Trip',
        special_offers: "Special Offers",
        winter_special: "Winter Special",
        winter_duration: "December - February",
        ski_adventure: "Ski Adventure",
        winter_price: "$500",
        per_person: "/person",
        ski_equipment: "Complete Ski Equipment",
        ski_instructor: "Professional Ski Instructor",
        mountain_resort: "Mountain Resort Stay",
        hot_drinks: "Free Hot Drinks",
        summer_special: "Summer Special",
        summer_duration: "June - August",
        beach_vacation: "Beach Vacation",
        summer_price: "$600",
        beach_access: "Private Beach Access",
        water_sports: "Water Sports",
        seaside_hotel: "Seaside Hotel",
        beach_activities: "Beach Activities",
        adventure_special: "Adventure Special",
        adventure_duration: "All Year Round",
        adventure_package: "Adventure Package",
        adventure_price: "$700",
        hiking: "Hiking Trips",
        camping: "Nature Camping",
        rafting: "River Rafting",
        photography: "Photography Tours",
        book_now: "Book Now",
        view_all_offers: "View All Offers",
        special_offers_badge: "Exclusive Offers",
        special_offers: "Our Special Offers",
        special_offers_subtitle: "Discover complete travel packages at competitive prices",
        moscow_package: "Moscow Package",
        moscow_package_title: "Complete Moscow Journey",
        hotel_5_stars: "5-star hotel for 7 nights",
        guided_tours_included: "Guided tours included",
        transfers_included: "Airport transfers included",
        moscow_price: "$1,499",
        petersburg_package: "St. Petersburg Package",
        petersburg_package_title: "Magic of St. Petersburg",
        hotel_4_stars: "4-star hotel for 5 nights",
        museum_tickets: "Famous museum tickets",
        river_cruise: "Neva River cruise",
        petersburg_price: "$1,299",
        russia_tour_package: "Complete Tour",
        russia_tour_title: "Discover Russia",
        three_cities: "Visit 3 major cities",
        all_transfers: "All inter-city transfers",
        full_support: "24/7 support",
        russia_tour_price: "$2,499",
        book_now: "Book Now",
        premium_services_badge: "Premium Services",
        premium_services: "Our Premium Services",
        premium_services_subtitle: "We offer a range of high-quality services",
        accommodation_service: "Accommodation Services",
        accommodation_description: "Book luxury hotels and furnished apartments in prime locations",
        luxury_hotels: "5-star hotels",
        furnished_apartments: "Luxury furnished apartments",
        best_locations: "Prime locations",
        flight_service: "Flight Booking",
        flight_description: "Book flights with all international airlines",
        best_prices: "Best prices",
        multiple_airlines: "Multiple options",
        flexible_dates: "Flexible dates",
        transport_service: "Transport Services",
        transport_description: "Providing comfortable and safe transportation for all your trips",
        airport_transfers: "Airport transfers",
        city_tours: "City tours",
        private_drivers: "Private driver",
    },
    ru: {
        brand_name: 'Учоба',
        tourism_site_title: 'Туризм в России Учоба',
        tourism_subtitle: 'Туризм в России',
        tourism: 'Туризм',
        study: 'Учеба',
        contact: 'Свяжитесь с нами',
        discover_russia: 'Откройте для себя Россию',
        tourism_hero_title: 'Откройте для себя Россию',
        tourism_hero_subtitle: 'Исключительные туры по красивейшим городам России',
        tourism_services: 'Наши туристические услуги',
        tourism_footer_description: 'Комплексные туристические услуги в России',
        tourism_title: "Незабываемое путешествие по России",
        tourism_description: "Исследуйте очаровательную красоту России, от исторических дворцов до захватывающих пейзажей",
        popular_destinations: 'Популярные направления',
        discover_places: 'Откройте для себя красивые места России',
        destinations_description: 'Исследуйте известные достопримечательности и очаровательные места России',
        moscow: 'Москва',
        moscow_description: 'Яркая и историческая столица России',
        landmarks: 'Достопримечательность',
        restaurants: 'Ресторан',
        hotels: 'Отель',
        main_attractions: 'Главные достопримечательности',
        red_square: 'Красная площадь',
        kremlin: 'Кремль',
        st_basil: 'Собор Василия Блаженного',
        best_time: 'Лучшее время для посещения: май-сентябрь',
        language: 'Язык: русский',
        currency: 'Валюта: российский рубль',
        saint_petersburg: 'Санкт-Петербург',
        petersburg_description: 'Город дворцов, искусства и культуры',
        hermitage: 'Эрмитаж',
        peterhof: 'Петергоф',
        church_spilled_blood: 'Храм Спаса на Крови',
        best_time_spb: 'Лучшее время для посещения: июнь-август',
        white_nights: 'Белые ночи: май-июль',
        moscow_distance: '4 часа от Москвы на поезде',
        sochi: 'Сочи',
        sochi_description: 'Красивый прибрежный город на Черном море',
        beaches: 'Пляж',
        ski_resorts: 'Горнолыжный курорт',
        rosa_khutor: 'Курорт Роза Хутор',
        olympic_park: 'Олимпийский парк',
        dendrarium: 'Дендрарий',
        best_time_sochi: 'Лето для пляжей, зима для катания на лыжах',
        climate: 'Умеренный климат круглый год',
        moscow_flight: '2 часа полета от Москвы',
        explore_destination: 'Исследовать направление',
        view_all_destinations: 'Посмотреть все направления',
        destinations: 'Направления',
        tourists: 'Туристов в год',
        tours: 'Организованных туров',
        explore_now: 'Исследовать сейчас',
        book_trip: 'Забронировать поездку',
        sochi_offers: 'Специальные предложения Сочи',
        sochi_offers_subtitle: 'Откройте для себя лучшие туристические предложения в Сочи',
        hero_badge: 'Откройте для себя Россию',
        hero_title: 'Исключительное путешествие по',
        hero_title_highlight: 'Волшебной России',
        hero_subtitle: 'Исследуйте потрясающую красоту России, от исторических дворцов до захватывающих пейзажей и богатой культуры',
        historic_palaces: 'Исторические дворцы',
        winter_views: 'Зимние пейзажи',
        russian_culture: 'Русская культура',
        explore_destinations: 'Исследовать направления',
        book_your_trip: 'Забронировать поездку',
        special_offers: "Специальные предложения",
        winter_special: "Зимнее предложение",
        winter_duration: "Декабрь - Февраль",
        ski_adventure: "Лыжное приключение",
        winter_price: "500$",
        per_person: "/человек",
        ski_equipment: "Полное лыжное снаряжение",
        ski_instructor: "Профессиональный инструктор",
        mountain_resort: "Проживание в горном курорте",
        hot_drinks: "Бесплатные горячие напитки",
        summer_special: "Летнее предложение",
        summer_duration: "Июнь - Август",
        beach_vacation: "Пляжный отдых",
        summer_price: "600$",
        beach_access: "Доступ к частному пляжу",
        water_sports: "Водные виды спорта",
        seaside_hotel: "Отель у моря",
        beach_activities: "Пляжные развлечения",
        adventure_special: "Приключение",
        adventure_duration: "Круглый год",
        adventure_package: "Пакет приключений",
        adventure_price: "700$",
        hiking: "Пешие походы",
        camping: "Кемпинг на природе",
        rafting: "Речной рафтинг",
        photography: "Фототуры",
        book_now: "Забронировать",
        view_all_offers: "Все предложения",
        special_offers_badge: "Эксклюзивные предложения",
        special_offers: "Наши специальные предложения",
        special_offers_subtitle: "Откройте для себя полные пакеты путешествия по конкурентным ценам",
        moscow_package: "Пакет Москва",
        moscow_package_title: "Полное путешествие по Москве",
        hotel_5_stars: "Отель 5 звезд на 7 ночей",
        guided_tours_included: "Гидированные туры включены",
        transfers_included: "Трансферы из аэропорта включены",
        moscow_price: "$1,499",
        petersburg_package: "Пакет Санкт-Петербург",
        petersburg_package_title: "Волшебство Санкт-Петербурга",
        hotel_4_stars: "Отель 4 звезды на 5 ночей",
        museum_tickets: "Билеты в знаменитые музеи",
        river_cruise: "Круиз по реке Нева",
        petersburg_price: "$1,299",
        russia_tour_package: "Полный тур",
        russia_tour_title: "Откройте для себя Россию",
        three_cities: "Посетите 3 основных города",
        all_transfers: "Все междугородние трансферы",
        full_support: "Поддержка 24/7",
        russia_tour_price: "$2,499",
        book_now: "Забронировать",
        premium_services_badge: "Премиум услуги",
        premium_services: "Наши премиум услуги",
        premium_services_subtitle: "Мы предлагаем ряд высококачественных услуг",
        accommodation_service: "Услуги по размещению",
        accommodation_description: "Бронирование люксовых отелей и меблированных апартаментов в лучших местах",
        luxury_hotels: "5-звездочные отели",
        furnished_apartments: "Люкс апартаменты",
        best_locations: "Лучшие локации",
        flight_service: "Бронирование авиабилетов",
        flight_description: "Бронирование билетов на все международные авиалинии",
        best_prices: "Лучшие цены",
        multiple_airlines: "Множество вариантов",
        flexible_dates: "Гибкие даты",
        transport_service: "Транспортные услуги",
        transport_description: "Предоставление комфортного и безопасного транспорта для всех ваших поездок",
        airport_transfers: "Трансфер из аэропорта",
        city_tours: "Городские туры",
        private_drivers: "Личный водитель",
    },
};

// تحديث لغة الصفحة السياحية
function updateTourismLanguage(lang) {
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        if (tourismTranslations[lang] && tourismTranslations[lang][key]) {
            if (element.tagName.toLowerCase() === 'input' || element.tagName.toLowerCase() === 'textarea') {
                element.placeholder = tourismTranslations[lang][key];
            } else {
                element.textContent = tourismTranslations[lang][key];
            }
        }
    });

    // تحديث عنوان الصفحة
    document.title = tourismTranslations[lang]['tourism_site_title'];

    // تحديث اتجاه الصفحة
    document.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    // تحديث الكلاسات النشطة لأزرار اللغة
    document.querySelectorAll('.dropdown-item').forEach(item => {
        item.classList.remove('active');
        if (item.getAttribute('data-lang') === lang) {
            item.classList.add('active');
        }
    });
}

// تحميل معرض الصور السياحية
function loadTourismGallery() {
    const tourismImages = [
        'https://source.unsplash.com/800x600/?russia,moscow',
        'https://source.unsplash.com/800x600/?russia,saint-petersburg',
        'https://source.unsplash.com/800x600/?russia,sochi',
        'https://source.unsplash.com/800x600/?russia,kremlin',
        'https://source.unsplash.com/800x600/?russia,winter-palace',
        'https://source.unsplash.com/800x600/?russia,black-sea'
    ];

    const gallery = document.getElementById('tourismGallery');
    if (gallery) {
        tourismImages.forEach(image => {
            const col = document.createElement('div');
            col.className = 'col-md-4 mb-4';
            col.innerHTML = `
                <div class="destination-card">
                    <div class="destination-image">
                        <img src="${image}" alt="السياحة في روسيا" class="img-fluid">
                    </div>
                </div>
            `;
            gallery.appendChild(col);
        });
    }
}

// تفعيل النماذج السياحية
document.addEventListener('DOMContentLoaded', function() {
    loadTourismGallery();
    
    // تفعيل تغيير اللغة
    const languageSelector = document.getElementById('languageSelector');
    if (languageSelector) {
        languageSelector.addEventListener('change', function() {
            updateTourismLanguage(this.value);
        });
    }
    
    // تفعيل نموذج حجز الرحلات
    const bookingForm = document.getElementById('tourismBookingForm');
    if (bookingForm) {
        bookingForm.addEventListener('submit', function(e) {
            e.preventDefault();
            // إضافة منطق معالجة نموذج الحجز هنا
        });
    }
});

// تفعيل التأثيرات الحركية للصفحة السياحية
window.addEventListener('scroll', function() {
    const navbar = document.querySelector('.tourism-navbar');
    if (navbar) {
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }
    }
});
